print("Hello Word!")
print("Hello Again!")
print("I like to type this！")
print("Thank you!")

print("I will now count my chickens:")
print("Hens",30+5)
print("Roosters",20+8)
print("Now,I will count my eggs:")
print(3+2+8*6-9)
print("Is it true that 5-3<2-7?")
print(5-3<2-7)
print("What is 5-3?",5-3)
print("What is 2-7?",2-7)
print("Oh,that is why it's false!")
print("How about some more.")
print("Is it greater?",5>-2)
print("Is it greater or equal?",5>=-2)
print("Is it less or equal?",5<=-2)
